### ISSUE TITLE
error when not selecting file

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/ecogVIS#112]
The script crashes when no NWB file is selected on startup

```python
(ecogvis) Bens-MacBook-Pro-2:ecogVIS bendichter$ ecogvis
Traceback (most recent call last):
  File "/Users/bendichter/opt/anaconda3/envs/ecogvis/bin/ecogvis", line 11, in <module>
    load_entry_point('ecogvis', 'console_scripts', 'ecogvis')()
  File "/Users/bendichter/dev/ecogVIS/ecogvis/ecogvis.py", line 1179, in cmd_line_shortcut
    main(source_path=source_path, metafile=metafile)
  File "/Users/bendichter/dev/ecogVIS/ecogvis/ecogvis.py", line 1142, in main
    ex = Application(source_path=source_path, metafile=metafile)
  File "/Users/bendichter/dev/ecogVIS/ecogvis/ecogvis.py", line 106, in __init__
    self.model = TimeSeriesPlotter(self)
  File "/Users/bendichter/dev/ecogVIS/ecogvis/functions/subFunctions.py", line 35, in __init__
    raise TypeError("Invalid file type")
TypeError: Invalid file type
```

**Comment by luiztauffer** [comment]
fixed with 9ff8341c48fe48254195b92f384a5523c10ba156
