### ISSUE TITLE
How to load HTK data?

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/ecogVIS#115]
When I select a RawHTK folder, I get 

```python
reading htk acquisition...
Traceback (most recent call last):
  File "/Users/bendichter/dev/ecogVIS/ecogvis/ecogvis.py", line 519, in open_htk_dir
    htk_config=w.htk_config,
  File "/Users/bendichter/dev/ecogVIS/ecogvis/functions/htk_to_nwb/chang2nwb.py", line 287, in chang2nwb
    ecog_rate, data = readhtks(ecog_path)
  File "/Users/bendichter/dev/ecogVIS/ecogvis/functions/htk_to_nwb/chang2nwb.py", line 63, in readhtks
    numbers = [f.name.split('.')[0].split('Wav')[1] for f in Path(htk_path).glob('*.htk')]
  File "/Users/bendichter/dev/ecogVIS/ecogvis/functions/htk_to_nwb/chang2nwb.py", line 63, in <listcomp>
    numbers = [f.name.split('.')[0].split('Wav')[1] for f in Path(htk_path).glob('*.htk')]
IndexError: list index out of range
```

**Comment by luiztauffer** [comment]
It seems like its not finding files with the specific names format. Are you using the RawHTK folder that was shared with us? Its content should look like this:

![image](https://user-images.githubusercontent.com/24541631/87386144-053a6480-c5ca-11ea-995a-9ec8e6ca16d3.png)

**Comment by bendichter** [comment]
fixed OSX-specific issue
