### ISSUE TITLE
loading error

### ISSUE THREAD

**Issue by LauraGwilliams** [catalystneuro/ecogVIS#118]
Hi there! I am trying to load a .nwb file into ecogVis and I am getting the error pasted below. I think it is not an issue with the .nwb file, because I am using the EC203_B2.nwb file that was used in the Chang Lab workshop ~a month ago. 

I have tried uninstalling and re-installing the package but this doesn't seem to help. 

My steps are:

(1) activate ecog_vis env
(2) start the ecogVis gui
(3) enter my name
(4) navigate File > Open From > NWB > EC203_B2.nwb

Is there any chance that this is due to using MacOS Catalina? This worked fine on my old laptop where I was using Mojave.

Thank you so much!
Laura

`(ecog_vis) lauragwilliams@Lauras-MBP ecogVIS % ecogVis 
/Users/lauragwilliams/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/hdmf/spec/namespace.py:470: UserWarning: ignoring namespace 'hdmf-common' because it already exists
  warn("ignoring namespace '%s' because it already exists" % ns['name'])
/Users/lauragwilliams/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/hdmf/spec/namespace.py:470: UserWarning: ignoring namespace 'core' because it already exists
  warn("ignoring namespace '%s' because it already exists" % ns['name'])
/Users/lauragwilliams/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/hdmf/spec/namespace.py:470: UserWarning: ignoring namespace 'ndx-ecog' because it already exists
  warn("ignoring namespace '%s' because it already exists" % ns['name'])
No 'preprocessed' data in 'processing' group.
No 'high_gamma' data in 'processing' group.
Traceback (most recent call last):
  File "/Users/lauragwilliams/git_packages/forked/ecogVIS/ecogvis/ecogvis.py", line 165, in <lambda>
    action_open_nwb.triggered.connect(lambda: self.open_another_file(None))
  File "/Users/lauragwilliams/git_packages/forked/ecogVIS/ecogvis/ecogvis.py", line 505, in open_another_file
    self.model = TimeSeriesPlotter(self)
  File "/Users/lauragwilliams/git_packages/forked/ecogVIS/ecogvis/functions/subFunctions.py", line 108, in __init__
    aux_mask = self.electrodes_table[self.electrical_series_channel_ids]['bad']
  File "/Users/lauragwilliams/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/hdmf/common/table.py", line 681, in __getitem__
    ret = self.get(key)
  File "/Users/lauragwilliams/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/hdmf/common/table.py", line 759, in get
    ret[name] = [col.get(arg, df=df, **kwargs) for i in arg]
  File "/Users/lauragwilliams/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/hdmf/common/table.py", line 759, in <listcomp>
    ret[name] = [col.get(arg, df=df, **kwargs) for i in arg]
  File "/Users/lauragwilliams/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/hdmf/common/table.py", line 51, in get
    return super().get(key)
  File "/Users/lauragwilliams/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/hdmf/container.py", line 477, in get
    return self.data[args]
  File "/Users/lauragwilliams/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/hdmf/backends/hdf5/h5_utils.py", line 180, in __getitem__
    ref = super().__getitem__(arg)
  File "/Users/lauragwilliams/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/hdmf/query.py", line 137, in __getitem__
    return self.dataset[idx]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/lauragwilliams/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 553, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/Users/lauragwilliams/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/h5py/_hl/selections.py", line 94, in select
    sel[args]
  File "/Users/lauragwilliams/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/h5py/_hl/selections.py", line 261, in __getitem__
    start, count, step, scalar = _handle_simple(self.shape,args)
  File "/Users/lauragwilliams/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/h5py/_hl/selections.py", line 453, in _handle_simple
    args = _expand_ellipsis(args, len(shape))
  File "/Users/lauragwilliams/anaconda3/envs/ecog_vis/lib/python3.7/site-packages/h5py/_hl/selections.py", line 440, in _expand_ellipsis
    raise TypeError("Argument sequence too long")
TypeError: Argument sequence too long`

**Comment by jersaal** [comment]
Install the correct version of pynwb with:
pip install pynwb==1.3.2
